'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PUSH_MODAL_WINDOW = exports.PUSH_MODAL_WINDOW = 'PUSH_MODAL_WINDOW';
var INSERT_MODAL_WINDOW = exports.INSERT_MODAL_WINDOW = 'INSERT_MODAL_WINDOW';
var POP_MODAL_WINDOW = exports.POP_MODAL_WINDOW = 'POP_MODAL_WINDOW';
var SHIFT_MODAL_WINDOW = exports.SHIFT_MODAL_WINDOW = 'SHIFT_MODAL_WINDOW';
var CLEAR_MODAL_WINDOWS = exports.CLEAR_MODAL_WINDOWS = 'CLEAR_MODAL_WINDOWS';